### ISSUE TITLE
Detected that custom integration 'edgeos' calls async_create_task

### ISSUE THREAD

**Issue by Greminn** [elad-bar/ha-edgeos#130]
Core 2024.5.0
Supervisor 2024.04.4
Operating System 12.2
Frontend 20240501.0

ha-edgeos 2.0.32

`2024-05-02 14:42:07.804 WARNING (SyncWorker_50) [homeassistant.helpers.frame] Detected that custom integration 'edgeos' calls async_create_task from a thread at custom_components/edgeos/core/managers/home_assistant.py, line 77: self._hass.async_create_task(self.async_send_heartbeat()), please report it to the author of the 'edgeos' custom integration
2024-05-02 14:42:07.804 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/edgeos/core/managers/home_assistant.py", line 77, in _send_heartbeat
    self._hass.async_create_task(self.async_send_heartbeat())
  File "/usr/src/homeassistant/homeassistant/core.py", line 816, in async_create_task
    self.verify_event_loop_thread("async_create_task")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'edgeos' calls async_create_task from a thread at custom_components/edgeos/core/managers/home_assistant.py, line 77: self._hass.async_create_task(self.async_send_heartbeat()). Please report it to the author of the 'edgeos' custom integration.
2024-05-02 14:42:08.136 WARNING (SyncWorker_8) [custom_components.edgeos.core.managers.home_assistant] Update in progress, will skip the request
2024-05-02 14:42:09.137 WARNING (SyncWorker_55) [custom_components.edgeos.core.managers.home_assistant] Update in progress, will skip the request
2024-05-02 14:42:10.138 WARNING (SyncWorker_3) [custom_components.edgeos.core.managers.home_assistant] Update in progress, will skip the request
2024-05-02 14:42:11.139 WARNING (SyncWorker_63) [custom_components.edgeos.core.managers.home_assistant] Update in progress, will skip the request
2024-05-02 14:42:12.140 WARNING (SyncWorker_13) [custom_components.edgeos.core.managers.home_assistant] Update in progress, will skip the request
2024-05-02 14:42:13.142 WARNING (SyncWorker_16) [custom_components.edgeos.core.managers.home_assistant] Update in progress, will skip the request
2024-05-02 14:42:14.142 WARNING (SyncWorker_6) [custom_components.edgeos.core.managers.home_assistant] Update in progress, will skip the request
2024-05-02 14:42:15.142 WARNING (SyncWorker_26) [custom_components.edgeos.core.managers.home_assistant] Update in progress, will skip the request
2024-05-02 14:42:16.143 WARNING (SyncWorker_7) [custom_components.edgeos.core.managers.home_assistant] Update in progress, will skip the request
2024-05-02 14:42:17.144 WARNING (SyncWorker_11) [custom_components.edgeos.core.managers.home_assistant] Update in progress, will skip the request
2024-05-02 14:42:18.145 WARNING (SyncWorker_12) [custom_components.edgeos.core.managers.home_assistant] Update in progress, will skip the request
2024-05-02 14:42:19.146 WARNING (SyncWorker_52) [custom_components.edgeos.core.managers.home_assistant] Update in progress, will skip the request
2024-05-02 14:42:20.146 WARNING (SyncWorker_42) [custom_components.edgeos.core.managers.home_assistant] Update in progress, will skip the request
2024-05-02 14:42:21.147 WARNING (SyncWorker_39) [custom_components.edgeos.core.managers.home_assistant] Update in progress, will skip the request
2024-05-02 14:42:22.148 WARNING (SyncWorker_45) [custom_components.edgeos.core.managers.home_assistant] Update in progress, will skip the request
2024-05-02 14:42:23.149 WARNING (SyncWorker_41) [custom_components.edgeos.core.managers.home_assistant] Update in progress, will skip the request
2024-05-02 14:42:24.150 WARNING (SyncWorker_29) [custom_components.edgeos.core.managers.home_assistant] Update in progress, will skip the request`

**Comment by elad-bar** [comment]
It is the same as #129, i'm working on it and hope to have a fix during the upcoming weekend

**Comment by Greminn** [comment]
> It is the same as #129, i'm working on it and hope to have a fix during the upcoming weekend

Thank you!

**Comment by Gunth** [comment]
Also have this kind of error with the new update 2024.5, nothing working anymore.
Not sure if it's related but I've a lot of "Update in progress, will skip the request"

**Comment by elad-bar** [comment]
It will not work due to breaking change in HA, you can disable the integration up until it will get fixed

**Comment by elad-bar** [comment]
released [v2.1.0](https://github.com/elad-bar/ha-edgeos/releases/tag/v2.1.0), pls check and report

**Comment by Gunth** [comment]
@elad-bar  After updating and re-enabling the component it failed to setup with this error:

`2024-05-02 20:37:08.963 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: name=custom_components.edgeos, message=['Failed to load EdgeOS, error: , line: 36'], level=ERROR, source=('custom_components/edgeos/__init__.py', 73), timestamp=1714675028.941197, exception=, count=1, first_occurred=1714675028.941197>`

...

`2024-05-02 20:37:55.925 DEBUG (Recorder) [homeassistant.components.recorder.core] Processing task: <Event system_log_event[L]: name=custom_components.edgeos, message=['Failed to load EdgeOS, error: , line: 36'], level=ERROR, source=('custom_components/edgeos/__init__.py', 73), timestamp=1714675028.941197, exception=, count=1, first_occurred=1714675028.941197>`

**Comment by Greminn** [comment]
Same here... Updated, re-ebabled, asked me to restart HA, then it fails to load:

<img width="712" alt="image" src="https://github.com/elad-bar/ha-edgeos/assets/81659316/2999a4dd-24f9-49de-b5bb-063ba32b56f8">

2024-05-03 07:57:31.774 ERROR (MainThread) [custom_components.edgeos] Failed to load EdgeOS, error: , line: 36

**Comment by elad-bar** [comment]
Please remove, restart and add again

**Comment by snowgumrd** [comment]
Same issue, but removing restarting and re-adding worked for me! Thanks for your hard work.

**Comment by Greminn** [comment]
Removed and re-added worked, however I have noticed that UBNT Interface ETHX Status has changed from a binary sensor to a switch, which results in the following error: 

2024-05-03 12:14:00.104 ERROR (MainThread) [custom_components.edgeos.data_processors.interface_processor] Failed to extract Interfaces data, Error: 'switch' is not a valid InterfaceTypes, Line: 105

**Comment by Greminn** [comment]
Also, you might want to check something, my sensor.ubnt_interface_eth4_received_rate (ETH4 is my WAN port), has a B/s of 367,075,892,489.0 which is VERY fast :)

I have some template helpers setup like this:

{{ states('sensor.ubnt_interface_eth4_received_rate') | multiply(0.000010) | round(1) }}
{{ states('sensor.ubnt_interface_eth4_sent_rate') | multiply(0.000010) | round(1) }}

ETH4 Send Rate is same as it was before update, but  ETH4 Received date is 3,670,932.0 Mbit/s

**Comment by hgstanton** [comment]
Worked brilliantly until the upgrade to 2024.5.
Removed, restarted, download and reinstall per above.
Can't login to server during 'add integration' install.
Address and login credentials work on Firefox.
Hope this helps, thanks for your work you have so generously donated to the world!


This error originated from a custom integration.

Logger: custom_components.edgeos.managers.flow_manager
Source: custom_components/edgeos/managers/flow_manager.py:106
integration: Ubiquiti EdgeOS Routers (documentation, issues)
First occurred: 8:31:49 PM (3 occurrences)
Last logged: 8:35:55 PM

Failed to create integration, Error Key: invalid_server_details
Failed to create integration, Error Key: invalid_admin_credentials

**Comment by Greminn** [comment]
Note: Im on 2024.5 and the remove, restart, add process worked fine for me with v2.1.0.

Core 2024.5.0
Supervisor 2024.04.4
Operating System 12.2

**Comment by hgstanton** [comment]
> Worked brilliantly until the upgrade to 2024.5. Removed, restarted, download and reinstall per above. Can't login to server during 'add integration' install. Address and login credentials work on Firefox. Hope this helps, thanks for your work you have so generously donated to the world!
> 
> This error originated from a custom integration.
> 
> Logger: custom_components.edgeos.managers.flow_manager Source: custom_components/edgeos/managers/flow_manager.py:106 integration: Ubiquiti EdgeOS Routers (documentation, issues) First occurred: 8:31:49 PM (3 occurrences) Last logged: 8:35:55 PM
> 
> Failed to create integration, Error Key: invalid_server_details Failed to create integration, Error Key: invalid_admin_credentials

After hard power off / on cycle adding integration worked first time. Sorry, should have done that first......

**Comment by elad-bar** [comment]
> > Worked brilliantly until the upgrade to 2024.5. Removed, restarted, download and reinstall per above. Can't login to server during 'add integration' install. Address and login credentials work on Firefox. Hope this helps, thanks for your work you have so generously donated to the world!
> > This error originated from a custom integration.
> > Logger: custom_components.edgeos.managers.flow_manager Source: custom_components/edgeos/managers/flow_manager.py:106 integration: Ubiquiti EdgeOS Routers (documentation, issues) First occurred: 8:31:49 PM (3 occurrences) Last logged: 8:35:55 PM
> > Failed to create integration, Error Key: invalid_server_details Failed to create integration, Error Key: invalid_admin_credentials
> 
> After hard power off / on cycle adding integration worked first time. Sorry, should have done that first......

Happy to see, sorry for the mess with the breaking change, tried my best to avoid it

**Comment by elad-bar** [comment]
> Also, you might want to check something, my sensor.ubnt_interface_eth4_received_rate (ETH4 is my WAN port), has a B/s of 367,075,892,489.0 which is VERY fast :)
> 
> I have some template helpers setup like this:
> 
> {{ states('sensor.ubnt_interface_eth4_received_rate') | multiply(0.000010) | round(1) }} {{ states('sensor.ubnt_interface_eth4_sent_rate') | multiply(0.000010) | round(1) }}
> 
> ETH4 Send Rate is same as it was before update, but ETH4 Received date is 3,670,932.0 Mbit/s

If that still happens, can you pls provide diagnostic file (or would like to analyze it first)?

Thanks

**Comment by GigiPompieru** [comment]
> Removed and re-added worked, however I have noticed that UBNT Interface ETHX Status has changed from a binary sensor to a switch, which results in the following error:
> 
> 2024-05-03 12:14:00.104 ERROR (MainThread) [custom_components.edgeos.data_processors.interface_processor] Failed to extract Interfaces data, Error: 'switch' is not a valid InterfaceTypes, Line: 105

yep, the interface changed. and getting the same error

**Comment by elad-bar** [comment]
Will add back support for switch interface later today

**Comment by elad-bar** [comment]
release [v2.1.1](https://github.com/elad-bar/ha-edgeos/releases/tag/v2.1.1) with fix for the switch interface and missing functionality of units

**Comment by Greminn** [comment]
Uninstall, restart and re-install (after updating to 2024.5.1 FYI) seems to have fixed things from a logging perspective, however I note that UBNT Interface ETHX Status has actually disappeared from the entities:

<img width="1027" alt="image" src="https://github.com/elad-bar/ha-edgeos/assets/81659316/33e2f248-c867-40bf-992a-7a9dc557252e">

The received_rate is fixed, however I am a little disappointed that I dont have 4,000,000 Mbit/sec internet anymore! :) 

<img width="559" alt="image" src="https://github.com/elad-bar/ha-edgeos/assets/81659316/85a2a75e-c692-4dfd-9b52-f29d74f809f1">

**Comment by Gunth** [comment]
I still don’t have my wiregard interface anymore with the latest release ( 2.1.1 )

and also the status for each interface is not there anymore ..


```
Logger: custom_components.edgeos.data_processors.interface_processor
Source: custom_components/edgeos/data_processors/interface_processor.py:115
integration: Ubiquiti EdgeOS Routers (documentation, issues)
First occurred: 20:32:58 (7361 occurrences)
Last logged: 22:26:07

Failed to extract Interfaces data, Error: 'wireguard' is not a valid InterfaceTypes, Line: 105
```

**Comment by dolenec** [comment]
![SmartSelect_20240504_013538_Home Assistant.jpg](https://github.com/elad-bar/ha-edgeos/assets/16633222/4ee13ecd-f41a-4aba-b9b1-7ef8d11cd731)

HA 2024.5.1 and integration 2.1.1.

Error stil presented..

**Comment by elad-bar** [comment]
@dolenec to upgrade into 2.1.x, you will need to remove the previous set up of the integration, restart and re sdd it

@Gunth @Greminn pls report it in another issue with logs and diagnostic data

Thanks

**Comment by elad-bar** [comment]
closing this issue as it was solved, other issues are reported or resolved as well
